/*
 * djc.h - DOS Java Compiler Driver
 *
 * Integrated compiler that orchestrates all compilation phases:
 * Lexer -> Parser -> Semantic Analysis -> Code Generation
 *
 * Uses file-based pipeline with intermediate files.
 */

#ifndef DJC_COMPILER_H
#define DJC_COMPILER_H

#include <stdio.h>
#include "../../src/types.h"

/* Exit codes */
#define EXIT_SUCCESS    0
#define EXIT_ERROR      1
#define EXIT_USAGE      2

/* Maximum path length for DOS (8.3 format + path) */
#define MAX_PATH_LEN    256

/* Maximum error message length */
#define MAX_ERROR_LEN   256

/*
 * CompilerContext - Main compiler state
 * 
 * Holds all state for a single compilation, including:
 * - Input/output file paths
 * - Compilation options
 * - Statistics
 * - Error tracking
 */
typedef struct {
    /* Input/Output files */
    char source_file[MAX_PATH_LEN];     /* Input .java file */
    char output_file[MAX_PATH_LEN];     /* Output .djc file */
    
    /* Intermediate files */
    char tok_file[MAX_PATH_LEN];        /* Token file (.tok) */
    char ast_file[MAX_PATH_LEN];        /* AST file (.ast) */
    char sym_file[MAX_PATH_LEN];        /* Symbol table file (.sym) */
    
    /* Compilation options */
    int keep_intermediates;             /* Keep intermediate files */
    int verbose;                        /* Verbose output */
    
    /* Statistics */
    uint16_t line_count;                /* Number of source lines */
    uint16_t token_count;               /* Number of tokens */
    uint16_t node_count;                /* Number of AST nodes */
    uint16_t symbol_count;              /* Number of symbols */
    uint16_t bytecode_size;             /* Size of generated bytecode */
    
    /* Error tracking */
    int has_error;                      /* Error occurred flag */
    char error_message[MAX_ERROR_LEN]; /* Last error message */
} CompilerContext;

/*
 * Initialization and cleanup
 */

/* Initialize compiler context with default values */
void compiler_init(CompilerContext* ctx);

/* Cleanup compiler context */
void compiler_cleanup(CompilerContext* ctx);

/*
 * Main compilation function
 */

/* Run full compilation pipeline: Lexer -> Parser -> Semantic -> Codegen */
int compiler_compile(CompilerContext* ctx);

/*
 * Phase execution functions
 */

/* Execute lexical analysis phase */
int run_lexer_phase(CompilerContext* ctx);

/* Execute parsing phase */
int run_parser_phase(CompilerContext* ctx);

/* Execute semantic analysis phase */
int run_semantic_phase(CompilerContext* ctx);

/* Execute code generation phase */
int run_codegen_phase(CompilerContext* ctx);

/*
 * Utility functions
 */

/* Generate intermediate file names based on source file */
void generate_intermediate_filenames(CompilerContext* ctx);

/* Remove intermediate files */
void cleanup_intermediate_files(CompilerContext* ctx);

/* Check if a file exists */
int check_file_exists(const char* filename);

/* Extract base filename (without path and extension) */
void get_base_filename(const char* path, char* base, size_t base_size);

/*
 * Reporting functions
 */

/* Print compilation statistics */
void print_statistics(const CompilerContext* ctx);

/* Report error with details */
void report_error(const CompilerContext* ctx);

/* Print usage information */
void print_usage(const char* program_name);

/* Print version information */
void print_version(void);

/*
 * Command-line parsing
 */

/* Parse command-line arguments and populate context */
int parse_arguments(int argc, char* argv[], CompilerContext* ctx);

#endif /* DJC_COMPILER_H */


