#include "semantic.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/**
 * DOS Java Compiler - Semantic Analyzer Test Program
 * 
 * Tests semantic analysis on AST files generated by the parser.
 * Usage: test_semantic <ast_file> [symbol_file]
 */

static void print_usage(const char* program_name) {
    printf("DOS Java Compiler - Semantic Analyzer Test\n");
    printf("Usage: %s <ast_file> [symbol_file]\n", program_name);
    printf("\n");
    printf("Arguments:\n");
    printf("  ast_file     - Input AST file (from parser)\n");
    printf("  symbol_file  - Output symbol table file (default: symbols.sym)\n");
    printf("\n");
    printf("Example:\n");
    printf("  %s test.ast\n", program_name);
    printf("  %s test.ast test.sym\n", program_name);
}

int main(int argc, char* argv[]) {
    SemanticAnalyzer* analyzer;
    const char* ast_file;
    const char* symbol_file;
    int result;
    
    /* Check arguments */
    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }
    
    ast_file = argv[1];
    symbol_file = (argc >= 3) ? argv[2] : "symbols.sym";
    
    printf("DOS Java Semantic Analyzer Test\n");
    printf("================================\n");
    printf("AST file:    %s\n", ast_file);
    printf("Symbol file: %s\n", symbol_file);
    printf("\n");
    
    /* Allocate analyzer on heap (avoid stack overflow) */
    analyzer = (SemanticAnalyzer*)malloc(sizeof(SemanticAnalyzer));
    if (!analyzer) {
        printf("Error: Failed to allocate semantic analyzer\n");
        return 1;
    }
    
    /* Initialize semantic analyzer */
    printf("Initializing semantic analyzer...\n");
    if (semantic_init(analyzer, ast_file, symbol_file) != 0) {
        printf("Error: Failed to initialize semantic analyzer\n");
        printf("  - Check that AST file exists and is valid\n");
        free(analyzer);
        return 1;
    }
    
    printf("Loaded AST: %u nodes, %u bytes string pool\n",
           analyzer->total_nodes, analyzer->pool_size);
    printf("\n");
    
    /* Perform semantic analysis */
    printf("Performing semantic analysis...\n");
    printf("--------------------------------\n");
    
    result = semantic_analyze(analyzer);
    
    printf("--------------------------------\n");
    
    /* Print results */
    if (result == 0) {
        printf("\nSemantic analysis completed successfully!\n");
        printf("  Symbols: %u\n", analyzer->symtable->symbol_count);
        printf("  Errors:  0\n");
        
        /* Print symbol table */
        printf("\n");
        symtable_print(analyzer->symtable);
        
        /* Write symbol table to file */
        printf("\nWriting symbol table to %s...\n", symbol_file);
        if (symtable_write(analyzer->symtable, symbol_file) == 0) {
            printf("Symbol table written successfully\n");
        } else {
            printf("Warning: Failed to write symbol table\n");
        }
    } else {
        printf("\nSemantic analysis failed!\n");
        printf("  Errors: %u\n", analyzer->error_count);
        printf("\n");
        
        /* Print errors */
        semantic_print_errors(analyzer);
        
        /* Print symbol table anyway (for debugging) */
        if (analyzer->symtable->symbol_count > 0) {
            printf("\nPartial symbol table:\n");
            symtable_print(analyzer->symtable);
        }
    }
    
    /* Cleanup */
    semantic_cleanup(analyzer);
    free(analyzer);
    
    return result == 0 ? 0 : 1;
}

// Made with Bob
